version: '3'

services:
    backend:
      build:
        context: ./backend
      environment:
        - PORT=5000
        - MONGODB_URI=mongodb+srv://sudeep:sudeep@cluster0.cqfoz4h.mongodb.net/kanban?retryWrites=true&w=majority
      ports:
        - '5000:5000'
      networks:
        - nodekanban

    frontend:
      build:
        context: ./frontend
      environment:
        - NEXT_PUBLIC_API_URL=http://{local machine ip}:5000
      ports:
        - '3000:3000'
      depends_on:
        - backend
      networks:
        - nodekanban

networks:
  nodekanban:
    driver: bridge